# Generated by Django 3.0.4 on 2020-03-19 14:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RADIPACANOV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
